version: '2.4'

services:
  server:
    image: perfectfit
    build:
      context: .
    ports:
      - 3030:3030
      - 9229:9229
    volumes:
      - ./config/:/opt/app/config:delegated
      - ./src/:/opt/app/src:delegated
      - ./database/:/opt/app/database:delegated
      - ./__tests__/:/opt/app/__tests__:delegated
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:12.2-alpine
    user: postgres
    healthcheck:
      test: pg_isready -h 127.0.0.1
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=perfectfit-db

volumes:
  postgres-data:
